version: "3.8"

volumes:
  ui-dist:

  postgres-data:

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vortex
  scraper:
    build: scraper
    links:
      - postgres
    ports:
      - "3334:3334"
  server:
    build: server
    links:
      - postgres
  ui:
    build: ui
    links:
      - "server:server"
    ports:
      - "127.0.0.1:3000:80"
    volumes:
      - ui-dist:/usr/share/nginx/html
  ui-watcher:
    build:
      context: ui
      dockerfile: Dockerfile.watcher
    volumes:
      - ui-dist:/app/dist
      - ./ui/src:/app/src
      - ./ui/public:/app/public
